channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=24.0
- pip:
  - mlflow==2.11.1
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - packaging==20.9
  - psutil==5.9.4
  - pyyaml==6.0.2
  - scikit-learn==1.1.3
  - scipy==1.10.1
name: mlflow-env
