channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=24.0
- pip:
  - mlflow==2.11.1
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - packaging==23.2
  - psutil==5.9.4
  - pyyaml==5.4.1
  - scikit-learn==1.4.1.post1
  - scipy==1.8.1
name: mlflow-env
